
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  branch = "master"
  name = "github.com/PuerkitoBio/goquery"

[[constraint]]
  branch = "master"
  name = "github.com/bogem/id3v2"

[[constraint]]
  branch = "master"
  name = "github.com/cheggaaa/pb"

[[constraint]]
  branch = "master"
  name = "github.com/marcmak/calc"

[[constraint]]
  branch = "master"
  name = "github.com/michiwend/gomusicbrainz"

[[constraint]]
  branch = "master"
  name = "github.com/mitchellh/go-homedir"

[[constraint]]
  branch = "master"
  name = "github.com/otium/ytdl"

[[constraint]]
  branch = "master"
  name = "github.com/pkg/errors"

[[constraint]]
  branch = "master"
  name = "github.com/subosito/norma"

[[constraint]]
  branch = "master"
  name = "github.com/tidwall/gjson"
